name: Deploy to ECR
on:
  workflow_dispatch:


jobs:
  
  build:
    
    name: Build Image
    runs-on: ubuntu-latest

   
    steps:

    - name: Check out code
      uses: actions/checkout@0717577d45739eb3c851188b29f50ed6c0b2194e
    
    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@67fbcbb121271f7775d2e7715933280b06314838
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: eu-west-1

    - name: Login to Amazon ECR
      id: login-ecr
      uses: aws-actions/amazon-ecr-login@5a88a04c91d5c6f97aae0d9be790e64d9b1d47b7

    - name: Build, tag, and push image to Amazon ECR
      env:
        ECR_REGISTRY: ${{ secrets.ECR_REGISTRY }}
        ECR_REPOSITORY: docker-service
        IMAGE_TAG: latest
      run: |
        docker build -t $ECR_REGISTRY.dkr.ecr.eu-west-1.amazonaws.com/$ECR_REPOSITORY:$IMAGE_TAG .
        docker push $ECR_REGISTRY.dkr.ecr.eu-west-1.amazonaws.com/$ECR_REPOSITORY:$IMAGE_TAG
